### Site Settings ###
title               : Nathan Morin
description         : >-                               # >- means to ignore newlines until "url:"
                      Hi, I'm Nathan Morin. I am a technologist from Indiana who loves working 
                      at the intersection between great user design and innovative computer technology. 
                      I am interested in using my skills to solve the complex problems we face, 
                      believing innovative technology can alleviate many of our most pressing social problems. 
                      In particular, I believe recent increases in the availability of data and processing
                       capabilites present oportunities to automate decision making processes while greatly 
                       expanding the places where we can cost effectively apply inteligent analysis.

                      I graduated Purdue University majoring in Computer & Information Technology, 
                      minoring in Statistics in 2017 and now work at Eli Lilly. 
                      In my spare time I enjoy travel/photography, coding side projects, 
                      and working on my cars.

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : nathanamorin/nathanamorin.github.io    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]

### Author Info ###
author:
  name              : Nathan Morin
  image             : /assets/me.jpg
#  behance           : your_username
# dribbble          : your_username
  email             : contact@nathanmorin.com
#  facebook          : your_username
  github            : nathanamorin
# gitlab            : your_username
# instagram         : your_username
  linkedin          : nathanmorin
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : nathanamorin
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock